#define STRONE std::cout<<"Configuración ya encontrada. Aplicar ahora [A] o crear una nueva? [n] "
#define STRTWO std::cout<<"Nombre del dispositivo: "
#define STRTHREE std::cout<<"Nombre del mesh: "
#define STRFOUR std::cout<<"Frecuencia (predefinido: 2412): "
#define STRFIVE std::cout<<"Bandwidth (predefinido: \"HT20\"): "
#define STRSIX std::cout<<"No encriptado [1] (predef.), WPA2-PSK [2], WPA3-SAE [3]: "
#define STRSEVEN std::cout<<"Password: "
#define STREIGHT std::cout<<"IPv4 en formato xxx.xxx.xxx.xxx/mask: "
#define STRNINE std::cout<<"File de configuración creado!\nAplicar ahora? [Y/n] "
