#define STRTWO std::cout<<"Nombre del dispositivo: "
#define STRTHREE std::cout<<"Nombre del mesh: "
#define STRFOUR std::cout<<"Frecuencia (predefinido: 2412): "
#define STRFIVE std::cout<<"Bandwidth (predefinido: \"HT20\"): "
#define STRSIX std::cout<<"No encriptado [1] (predef.), AES (requiere una versión especìfica de wpa_supplicant) [2]: "
#define STRSEVEN std::cout<<"Password: "
#define STREIGHT std::cout<<"IPv4 en formato xxx.xxx.xxx.xxx/mask: "
#define STRNINE std::cout<<"File de configuración creado!\nAplicar ahora? [Y/n] "
#define STRTEN std::cout<<"Nombre de perfil: "
#define STRELEVEN std::cout<<"Info: el file de configuración ya existe.\n"
