#define STRONE std::cout<<"Configuration file found. Apply now [A] or create new? [n] "
#define STRTWO std::cout<<"Device: "
#define STRTHREE std::cout<<"Mesh name: "
#define STRFOUR std::cout<<"Frequency (default: 2412): "
#define STRFIVE std::cout<<"Bandwidth (default: \"HT20\"): "
#define STRSIX std::cout<<"Unencrypted [1] (def.), WPA2-PSK [2], WPA3-SAE [3]: "
#define STRSEVEN std::cout<<"Password: "
#define STREIGHT std::cout<<"IPv4 in xxx.xxx.xxx.xxx/mask format: "
#define STRNINE std::cout<<"Configuration file created!\nApply now? [Y/n] "
