#define STRTWO std::cout<<"Device: "
#define STRTHREE std::cout<<"Mesh name: "
#define STRFOUR std::cout<<"Frequency (default: 2412): "
#define STRFIVE std::cout<<"Bandwidth (default: \"HT20\"): "
#define STRSIX std::cout<<"Unencrypted [1] (def.), AES (requires specific wpa_supplicant build) [2]: "
#define STRSEVEN std::cout<<"Password: "
#define STREIGHT std::cout<<"IPv4 in xxx.xxx.xxx.xxx/mask format: "
#define STRNINE std::cout<<"Configuration file created!\nApply now? [Y/n] "
#define STRTEN std::cout<<"Profile name: "
#define STRELEVEN std::cout<<"Info: config already exists.\n"
